# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NTSAssignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  # Pods for NTSAssignment

  target 'NTSAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListModule' do
      use_frameworks!
      pod 'SDWebImage'
  end

  target 'ListModuleTests' do
    use_frameworks!
    pod 'SDWebImage'
  end

end
